accounts:
-   name: ENC[AES256_GCM,data:07Dk0Qc=,iv:CZT9qwYVIeLIx9roek4LBcWm1Zo/0rqdL2CaPiawQAE=,tag:t+n60Kf74d3lX7jqOKzvNg==,type:str]
    totpsecret: ENC[AES256_GCM,data:RBQ857YFOLQIuGqpjX1Tb4teFfptBiUEwWHzBsLXgBhDnpSvoDiBzSS3jLsgDS6m01nzQ97RulwAZadpr+0jkA==,iv:UIjc1OirNV0MpWQhf+2BLXOwgMqsINljhc2U5OxeNIQ=,tag:MWY5yU/vGKvmelboczN82w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    naclbox: []
    lastmodified: '2020-03-31T14:29:34Z'
    mac: ENC[AES256_GCM,data:Uxh27raJ927slMOVAB2sKmi+dfRAk9NLuutF1NyC7bB6KmV6M95padCEqDpiz+Q/0rlxz9E0IAhvBNRfRIlaY2B0p6v1jfTPiyJreWVbqmTkoK/yYktfBkgrRvbMgLqO/Qbg6CtI5+QZ40JOp/vbseP8ybax6Hn/DiMCD8aGX1I=,iv:qN4vNfCrGoMhlBQw1u/eYL3cVDvECYX5fKV2TqOV/AQ=,tag:ZGidkC/LdSv+Hxs5/TTLrw==,type:str]
    pgp:
    -   created_at: '2020-03-31T14:29:07Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMAyUpShfNkFB/AQgAWOQ0LvAyfWMOJsoICeTWPx++1h85gTxMRuACe8l+K3B+
            74yk21mmbZPKmLfWJD82/OhRAbulNi8z03sRtpdHa8jvTFNa9ntC9N5aLyWKVkaZ
            nOLW0HbqQXkS35ViDDnOqmjV1MBEIbDpWqsyfJSVd2eBXOhAI+56O4YQx+0KTUji
            6Wcs1UfwDlr/muuL7XWjgLndnEiz/jlFBVJ5gTtHHkxVoCxKwwb6Irlt/xbP3Jpx
            ud/a4QC8kiSdk+c4CdGmoGPl424gNqEMZIJvyHzyC8zQgbh3puNQGgfgbZo+M2M8
            QsSu+Ed+WqA/quK7an9BdzBOYSMV1i+CnUq9caGowdLgAeRchTY8VPdWDgrR0eAz
            qMUM4ZY+4ODgUOHXv+Bd4h6imUjgleWc1Kp2/KYtDKiTN3Bg5g+m5lSZjS5CtDL8
            NONxJ2HnS+AP5J4XKqPRMOQxYopyngun6/nieuA5feGYpAA=
            =HnoL
            -----END PGP MESSAGE-----
        fp: FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
    unencrypted_suffix: _unencrypted
    version: 3.4.0
