version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: gpg --import sops_functional_tests_key.asc
      - run: go run main.go test1
workflows:
  version: 2
  test:
    jobs:
      - test