name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - docs/**

jobs:
  test:
    name: Go ${{ matrix.go-version }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        go-version: [1.22.x, 1.23.x]
        platform: [ubuntu-latest]

    steps:
      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run mod tidy
        run: go mod tidy

      - name: Run vet
        run: go vet ./...

      - name: Run fmt
        run: go fmt ./...

      - name: Restore go/toolchain lines of go.mod
        run: python3 .github/utils/patch-go.mod.py

      - name: Check if directory is clean
        run: git diff --exit-code

      - name: Run mod tidy again
        run: go mod tidy

      - name: Import test key
        run: gpg --import sops_functional_tests_key.asc

      - name: Run tests
        run: go test -v -race ./...

      - name: Run main.go test1
        run: go run main.go test1
