name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - docs/**

jobs:
  test:
    name: Go ${{ matrix.go-version }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19.x, 1.20.x]
        platform: [ubuntu-latest]

    steps:
      - name: Install Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run mod tidy
        run: go mod tidy

      - name: Run vet
        run: go vet ./...

      - name: Run fmt
        run: go fmt ./...

      - name: Check if directory is clean
        run: git diff --exit-code

      - name: Import test key
        run: gpg --import sops_functional_tests_key.asc

      - name: Run tests
        run: go test -v -race ./...

      - name: Run main.go test1
        run: go run main.go test1
